# Generated by Django 3.2.5 on 2021-08-06 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testpost', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=10000)),
                ('date', models.DateTimeField()),
                ('room', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameModel(
            old_name='Testclass',
            new_name='Room',
        ),
    ]
