# Generated by Django 3.2.5 on 2021-08-06 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testpost', '0002_auto_20210806_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymessage',
            name='user',
            field=models.CharField(default='anonymus', max_length=100),
        ),
    ]
