# Generated by Django 3.2.5 on 2021-08-06 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testpost', '0003_mymessage_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='name',
            new_name='room_name',
        ),
        migrations.AddField(
            model_name='room',
            name='username',
            field=models.CharField(default='AnonymusUser', max_length=100),
        ),
        migrations.AlterField(
            model_name='mymessage',
            name='user',
            field=models.CharField(default='AnonymusUser', max_length=100),
        ),
    ]
