# Generated by Django 3.2.5 on 2021-08-06 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testpost', '0004_auto_20210806_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='username',
        ),
    ]
