# Generated by Django 3.2.5 on 2021-08-07 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testpost', '0006_rename_room_name_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymessage',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
