# Generated by Django 3.2.5 on 2021-08-07 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testpost', '0008_alter_mymessage_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymessage',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testpost.room'),
        ),
    ]
