# Generated by Django 3.2.5 on 2021-08-07 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testpost', '0009_alter_mymessage_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymessage',
            name='room',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
