# Generated by Django 3.2.5 on 2021-08-24 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testpost', '0011_auto_20210824_1300'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='joined',
            options={'verbose_name_plural': 'Joined'},
        ),
        migrations.AlterField(
            model_name='joined',
            name='phone',
            field=models.PositiveBigIntegerField(max_length=1000),
        ),
    ]
